spring:
  application:
    name: ins
api:
  layout:
    enabled: false

mailgen:
  templateLocation: "classpath:templates"
  defaultOnMissing: "LEAVE"                        # LEAVE | EMPTY | ERROR
  defaultLineEndings: "LF"                         # LF | CRLF
